### ISSUE TITLE
Result table contains wrong marks

### ISSUE THREAD

**Issue by alexyush** [aleksei-berezkin/css-puzzler#14]
Hi, Aleksei

It looks like there is bug with result table. If you look at first screenshot you will see that first column does not contain error, but I did an error on the second question... Look at the others screenschots... 
But total count of correct answers is correct...

![image](https://user-images.githubusercontent.com/11176196/151191894-99031ce5-445a-4756-a28e-ef5e71593cd6.png)
![image](https://user-images.githubusercontent.com/11176196/151190544-a79b32c4-9f90-4226-9d1e-4d9e8f5166f4.png)
![image](https://user-images.githubusercontent.com/11176196/151190566-75209060-b570-4ba7-935a-5cdb5b78d4d4.png)

**Comment by aleksei-berezkin** [comment]
Hi Alexey. Thanks for your report. I implemented result table to group all correct marks on the left, and wrong answers on the right, disregarding their actual order, so it shows kinda per-topic-score like 4 (correct) : 1 (wrong). However if it seems misleading no problem to change this.

**Comment by alexyush** [comment]
Thank you for answer.
It was misleading for me because it is intuitive to think that result table should keep order of the puzzles...
I think It is suitable for such cases to add some short description about ordering of the correct answers 
But it is up to you.
